### PR TITLE
Convert standup.js to coffeescript to support documentation

### PR DESCRIPTION
**Pull request by JensDebergh**
I've converted and tested the transition to coffeescript.
Hubot kept complaining about *old deprecated syntax* and wasn't listing the hubot commands when trying the command `hubot help`.

screen shot 2015-09-30 at 11 36 12

### CODE REVIEW

**Comment by shaundon** [comment]
I guess I need to get over my dislike of coffeescript! Thanks for the PR :smile:

**Comment by JensDebergh** [comment]
@shaundon I feel your pain. The only reason I'm doing this is because I actually want to see the documentation. Converting to ES6 would be the next step for scripts.

**Comment by shaundon** [comment]
Definitely - I've only used ES6 a little bit when playing around with React, I do need an excuse to use it properly!

**Comment by JensDebergh** [comment]
@shaundon Could you bump the version number on this npm package and redeploy to npm please?
I've also created a package with the exact same codebase for testing purposes and I'm still using it now. 

I'd like to switch over to the official npm package and remove my npm package with it. :8ball:

**Comment by shaundon** [comment]
Done - sorry for forgetting. I wish NPM did it automatically like Bower!

**Comment by JensDebergh** [comment]
Thanks for the quick reply :+1:

**Comment by Ajnasz** [comment]
Guys, I think it wasn't a necessary change, the doc parser was fixed in pr #17 
Only the new version wasn't published to npm.
Also the current in npm has the version 0.0.7, in here on github it's 0.0.6. On github the pr #21 merged, but it's not published to npm.

**Comment by Ajnasz** [comment]
Actually you can use a script or a taskrunner (grunt with https://github.com/geddski/grunt-release) to do the git tag, git push, npm publish in one step.

**Pull request merged**
