### PR TITLE
Adding an environment variable to allow customization of the work week

### PR DESCRIPTION
**Pull request by LTheobald**
As mentioned in #19 excluding a day from the standup rotation, or changing what the work week is, can be a handy feature. The ability to change the cron for when to check for standups will achieve both of these.

The only thing I'm a little unhappy with is that it'll still say you're creating your standup on a "weekday", even if you change the cron to say Sat-Sun. Might change that to "workday" potentially? Any thoughts? Picky thing I know!

### CODE REVIEW

**Comment by LTheobald** [comment]
Also now prevents #31 from occurring.

**Comment by shaundon** [comment]
Hi @LTheobald, thanks for the PR. Would you mind resolving the conflicts before I merge this?

**Comment by LTheobald** [comment]
There you go :)

**Comment by shaundon** [comment]
Merged! Thanks 👍

**Pull request merged**
